### PR TITLE
Redirect writing-assistance-apis to webmachinelearning/writing-assistance-apis

### PR DESCRIPTION
**Pull request by anssiko**

### CODE REVIEW

**Comment by yoavweiss** [comment]
Hey! Can you add the relevant proposal repo and redirected spec to the description?

**Comment by anssiko** [comment]
Hi @yoavweiss! I should have provided more context. This is about setting up redirects for a repo that has already been transferred from WICG to a topic-specific WebML CG: https://webmachinelearning.github.io/writing-assistance-apis

This redirect will ensure that the old https://wicg.github.io/writing-assistance-apis/ (with hashes) will redirect to the new place. @cwilso is informed of this transfer and @dontcallmedom helped with the actual transfer.

Do you want me to update the commit message with this context or does this suffice?

**Review by yoavweiss — APPROVED** [review]
LGTM, but please update the commit message with the relevant context. Cheers :)

**Comment by anssiko** [comment]
@yoavweiss commit message updated, thanks for the review!

**Pull request merged**
